### ISSUE TITLE
Firefox update required

### ISSUE THREAD

**Issue by JkenzoS** [mhgschmidt/w10install#1]
Firefox version is outdated. ( release from february)
Due to this condition some functions are restricted.
For example the Amazon Prime video player shows the following error.

![firefox_videoplayer_error](https://user-images.githubusercontent.com/86467234/123396998-3a08b700-d5a2-11eb-8caf-a6b323892534.JPG)

**Comment by mhgschmidt** [comment]
- get new version here: https://ftp.mozilla.org/pub/firefox/releases/90.0.2/win64/en-US/Firefox%20Setup%2090.0.2.exe
- save as "firefox-setup.exe" in path c:\tools\software
- execute batch script:  c:\tools\scripts\install-firefox.cmd

included in master with commit 91237b7.
